In [1]:
import pandas as pd

In [2]:
d1 = {"key1":[1,2,3,4,5,6],
      "key2":[7,8,9,10,11,12],
      "key3":[13,14,15,16,17,18],
      "key4":[19,20,21,22,23,24]

}

In [19]:
df1 = pd.DataFrame(d1)

In [4]:
d2 = {"key1":[1,2,3,4,5],
      "key2":[7,8,9,10,11,12],
      "key3":[13,14,15,16,17,18],
      "key4":[19,20,21,22,23,24]

}

In [8]:
#pd.DataFrame(d2) # no. of elements must be equal

In [9]:
d3 = {"key1":[1,2,3,4,5,"Logan"],
      "key2":[7,8,9,10,11,12],
      "key3":[13,14,15,16,17,18],
      "key4":[19,20,21,22,23,24]

}

In [15]:
#df1 = pd.DataFrame(d1,index= ['a','b','c','d','e','f'])

In [11]:
d3 = {"key1":[1,2,3,4,5,"Logan"],
      "key2":[7,8,"Soni",10,11,12],
      "key3":[13,14,15,16,"is",18],
      "key4":[19,'a',21,22,23,"dog"]

}

In [16]:
df2 = pd.DataFrame(d3)

In [13]:
df2

key1  key2 key3 key4
0      1     7   13   19
1      2     8   14    a
2      3  Soni   15   21
3      4    10   16   22
4      5    11   is   23
5  Logan    12   18  dog

In [21]:
pd.merge(df1,df2)

key1 key2 key3 key4
0    1    7   13   19
1    4   10   16   22

In [20]:
df1

key1  key2  key3  key4
0     1     7    13    19
1     2     8    14    20
2     3     9    15    21
3     4    10    16    22
4     5    11    17    23
5     6    12    18    24

In [22]:
pd.merge(df1,df2, how = "inner", on = "key1" )

key1  key2_x  key3_x  key4_x key2_y key3_y key4_y
0    1       7      13      19      7     13     19
1    2       8      14      20      8     14      a
2    3       9      15      21   Soni     15     21
3    4      10      16      22     10     16     22
4    5      11      17      23     11     is     23

In [23]:
pd.merge(df1,df2, how = "inner", on = "key4" ) # see key

key1_x  key2_x  key3_x key4 key1_y key2_y key3_y
0       1       7      13   19      1      7     13
1       3       9      15   21      3   Soni     15
2       4      10      16   22      4     10     16
3       5      11      17   23      5     11     is

In [24]:
pd.merge(df1,df2, how = "left", on = "key4" ) # see show

key1_x  key2_x  key3_x key4 key1_y key2_y key3_y
0       1       7      13   19      1      7     13
1       2       8      14   20    NaN    NaN    NaN
2       3       9      15   21      3   Soni     15
3       4      10      16   22      4     10     16
4       5      11      17   23      5     11     is
5       6      12      18   24    NaN    NaN    NaN

In [25]:
pd.merge(df1,df2, how = "right", on = "key4" )

/tmp/ipykernel_2052/2351442753.py:1: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  pd.merge(df1,df2, how = "right", on = "key4" )


key1_x  key2_x  key3_x  key4 key1_y key2_y key3_y
0     1.0     7.0    13.0  19.0      1      7     13
1     NaN     NaN     NaN     a      2      8     14
2     3.0     9.0    15.0  21.0      3   Soni     15
3     4.0    10.0    16.0  22.0      4     10     16
4     5.0    11.0    17.0  23.0      5     11     is
5     NaN     NaN     NaN   dog  Logan     12     18

In [26]:
pd.merge(df1,df2, how = "outer", on = "key4" ) # complete merge operation,bring each and everything

/tmp/ipykernel_2052/3450722664.py:1: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  pd.merge(df1,df2, how = "outer", on = "key4" )


key1_x  key2_x  key3_x  key4 key1_y key2_y key3_y
0     1.0     7.0    13.0  19.0      1      7     13
1     2.0     8.0    14.0  20.0    NaN    NaN    NaN
2     3.0     9.0    15.0  21.0      3   Soni     15
3     4.0    10.0    16.0  22.0      4     10     16
4     5.0    11.0    17.0  23.0      5     11     is
5     6.0    12.0    18.0  24.0    NaN    NaN    NaN
6     NaN     NaN     NaN     a      2      8     14
7     NaN     NaN     NaN   dog  Logan     12     18

In [27]:
pd.merge(df1,df2, how = "outer", on = ["key4","key1"] )

/tmp/ipykernel_2052/2263629071.py:1: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  pd.merge(df1,df2, how = "outer", on = ["key4","key1"] )


key1  key2_x  key3_x  key4 key2_y key3_y
0    1.0     7.0    13.0  19.0      7     13
1    2.0     8.0    14.0  20.0    NaN    NaN
2    3.0     9.0    15.0  21.0   Soni     15
3    4.0    10.0    16.0  22.0     10     16
4    5.0    11.0    17.0  23.0     11     is
5    6.0    12.0    18.0  24.0    NaN    NaN
6      2     NaN     NaN     a      8     14
7  Logan     NaN     NaN   dog     12     18

In [41]:
d11 = {"a":[1,2,3,4,5,6],
      "b":[7,8,9,10,11,12],
      "c":[13,14,15,16,17,18],
      "d":[19,20,21,22,23,24]

}

In [42]:
d13 = {"key1":[1,2,3,4,5,"Logan"],
      "key2":[7,8,"Soni",10,11,12],
      "key3":[13,14,15,16,"is",18],
      "key4":[19,'a',21,22,23,"dog"]

}

In [43]:
df11 = pd.DataFrame(d11)

In [44]:
df13 = pd.DataFrame(d13)

In [77]:
pd.merge(d11,df13,how ="right",left_on = "a", right_on = "key1")

TypeError: Can only merge Series or DataFrame objects, a <class 'dict'> was passed

In [76]:
#df1.join(df2)

In [48]:
df1

key1  key2  key3  key4
0     1     7    13    19
1     2     8    14    20
2     3     9    15    21
3     4    10    16    22
4     5    11    17    23
5     6    12    18    24

In [49]:
df2

key1  key2 key3 key4
0      1     7   13   19
1      2     8   14    a
2      3  Soni   15   21
3      4    10   16   22
4      5    11   is   23
5  Logan    12   18  dog

In [53]:
d30 = {"key11":[1,2,3,4,5,"Logan"],
      "key21":[7,8,"Soni",10,11,12],
      "key31":[13,14,15,16,"is",18],
      "key41":[19,'a',21,22,23,"dog"]

}

In [54]:
d10 = {"key1":[1,2,3,4,5,6],
      "key2":[7,8,9,10,11,12],
      "key3":[13,14,15,16,17,18],
      "key4":[19,20,21,22,23,24]

}

In [69]:
df30 = pd.DataFrame(d30,index = [1,2,3,4,5,"New_index02"])

In [70]:
df10 = pd.DataFrame(d10,[1,2,3,4,5,"New_index01"])

In [71]:
df30.join(df10)

key11 key21 key31 key41  key1  key2  key3  key4
1                1     7    13    19   1.0   7.0  13.0  19.0
2                2     8    14     a   2.0   8.0  14.0  20.0
3                3  Soni    15    21   3.0   9.0  15.0  21.0
4                4    10    16    22   4.0  10.0  16.0  22.0
5                5    11    is    23   5.0  11.0  17.0  23.0
New_index02  Logan    12    18   dog   NaN   NaN   NaN   NaN

In [72]:
df10.join(df30, how = "inner")

key1  key2  key3  key4 key11 key21 key31 key41
1     1     7    13    19     1     7    13    19
2     2     8    14    20     2     8    14     a
3     3     9    15    21     3  Soni    15    21
4     4    10    16    22     4    10    16    22
5     5    11    17    23     5    11    is    23

In [73]:
df10.join(df30, how = "outer")

key1  key2  key3  key4  key11 key21 key31 key41
1             1.0   7.0  13.0  19.0      1     7    13    19
2             2.0   8.0  14.0  20.0      2     8    14     a
3             3.0   9.0  15.0  21.0      3  Soni    15    21
4             4.0  10.0  16.0  22.0      4    10    16    22
5             5.0  11.0  17.0  23.0      5    11    is    23
New_index01   6.0  12.0  18.0  24.0    NaN   NaN   NaN   NaN
New_index02   NaN   NaN   NaN   NaN  Logan    12    18   dog

In [74]:
df10.join(df30, how = "right")

key1  key2  key3  key4  key11 key21 key31 key41
1             1.0   7.0  13.0  19.0      1     7    13    19
2             2.0   8.0  14.0  20.0      2     8    14     a
3             3.0   9.0  15.0  21.0      3  Soni    15    21
4             4.0  10.0  16.0  22.0      4    10    16    22
5             5.0  11.0  17.0  23.0      5    11    is    23
New_index02   NaN   NaN   NaN   NaN  Logan    12    18   dog

In [75]:
df10.join(df30, how = "left")

key1  key2  key3  key4 key11 key21 key31 key41
1               1     7    13    19     1     7    13    19
2               2     8    14    20     2     8    14     a
3               3     9    15    21     3  Soni    15    21
4               4    10    16    22     4    10    16    22
5               5    11    17    23     5    11    is    23
New_index01     6    12    18    24   NaN   NaN   NaN   NaN

In [78]:
# join focus on index Matching, and Merge is value matching on column, but meaning of right, left, inner, outer, join is same as in SQL
# concat is joining table horizontally axis 0 or vertically axis 1

In [83]:
pd.concat([df10,df30],axis = 1)

key1  key2  key3  key4  key11 key21 key31 key41
1             1.0   7.0  13.0  19.0      1     7    13    19
2             2.0   8.0  14.0  20.0      2     8    14     a
3             3.0   9.0  15.0  21.0      3  Soni    15    21
4             4.0  10.0  16.0  22.0      4    10    16    22
5             5.0  11.0  17.0  23.0      5    11    is    23
New_index01   6.0  12.0  18.0  24.0    NaN   NaN   NaN   NaN
New_index02   NaN   NaN   NaN   NaN  Logan    12    18   dog

In [85]:
pd.concat([df10,df30],axis = 0)

key1  key2  key3  key4  key11 key21 key31 key41
1             1.0   7.0  13.0  19.0    NaN   NaN   NaN   NaN
2             2.0   8.0  14.0  20.0    NaN   NaN   NaN   NaN
3             3.0   9.0  15.0  21.0    NaN   NaN   NaN   NaN
4             4.0  10.0  16.0  22.0    NaN   NaN   NaN   NaN
5             5.0  11.0  17.0  23.0    NaN   NaN   NaN   NaN
New_index01   6.0  12.0  18.0  24.0    NaN   NaN   NaN   NaN
1             NaN   NaN   NaN   NaN      1     7    13    19
2             NaN   NaN   NaN   NaN      2     8    14     a
3             NaN   NaN   NaN   NaN      3  Soni    15    21
4             NaN   NaN   NaN   NaN      4    10    16    22
5             NaN   NaN   NaN   NaN      5    11    is    23
New_index02   NaN   NaN   NaN   NaN  Logan    12    18   dog

In [86]:
import numpy as np

In [87]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_in

In [88]:
l = [1,2,3,4,4]

In [90]:
type(l)

list

In [92]:
a = np.array(l)

In [93]:
type(a)

numpy.ndarray

In [94]:
a

array([1, 2, 3, 4, 4])

In [96]:
a1 = np.array([[1,2,3],[4,5,6]])

In [97]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
a2 = np.array([[[1,2,3],[4,5,6]]])

In [98]:
type(a1)

numpy.ndarray

In [100]:
a.ndim

1

In [101]:
a1.ndim

2

In [102]:
a2.ndim

3

In [103]:
a3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [104]:
a3.ndim

3

In [105]:
l

[1, 2, 3, 4, 4]

In [106]:
np.asarray(l)

array([1, 2, 3, 4, 4])

In [107]:
np.matrix(l)

matrix([[1, 2, 3, 4, 4]])

In [108]:
type(np.matrix(l))

numpy.matrix

In [109]:
np.matrix(l).ndim

2

In [110]:
np.asanyarray(a)

array([1, 2, 3, 4, 4])

In [111]:
np.asanyarray(l)

array([1, 2, 3, 4, 4])

In [113]:
np.asanyarray(np.matrix(l))

matrix([[1, 2, 3, 4, 4]])

In [114]:
# shalow copy and deep copy

In [115]:
a

array([1, 2, 3, 4, 4])

In [116]:
aa= a

In [117]:
aa

array([1, 2, 3, 4, 4])

In [118]:
a[0]

1

In [119]:
a[0] = 10

In [120]:
a

array([10,  2,  3,  4,  4])

In [121]:
aa

array([10,  2,  3,  4,  4])

In [122]:
a2 = np.copy(a)

In [123]:
a

array([10,  2,  3,  4,  4])

In [124]:
a2[3]=300

In [125]:
a2

array([ 10,   2,   3, 300,   4])

In [126]:
a

array([10,  2,  3,  4,  4])

In [128]:
np.fromfunction(lambda i,j : i==j, (3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [130]:
np.random.rand(2,3)

array([[0.88857581, 0.99252961, 0.64464358],
       [0.74054439, 0.22066776, 0.1577153 ]])

In [131]:
np.random.rand(2,3,2)

array([[[2.45552946e-01, 6.18424096e-01],
        [3.93985348e-01, 4.19521579e-01],
        [8.44453130e-01, 6.83395996e-01]],

       [[1.65577419e-01, 7.57644344e-01],
        [3.70518234e-01, 4.60164683e-01],
        [7.77950627e-01, 9.19749793e-05]]])

In [132]:
np.random.rand(2,3,2,2) # start counting from right for this one

array([[[[0.42285867, 0.39811189],
         [0.18051373, 0.2928897 ]],

        [[0.71381211, 0.44859319],
         [0.84094847, 0.9036761 ]],

        [[0.96350948, 0.68993844],
         [0.65822582, 0.86644455]]],


       [[[0.04879453, 0.54717512],
         [0.34338302, 0.01698814]],

        [[0.03718312, 0.02981122],
         [0.25415542, 0.5851881 ]],

        [[0.9183245 , 0.40968713],
         [0.21846738, 0.45439124]]]])

In [133]:
np.random.randn(3,4,4) # follows normal distribution, mean 0, std is 1

array([[[-0.34147912, -0.85321427, -0.30706405, -0.05893907],
        [-0.84287879,  0.70762432,  0.28363181, -0.72831215],
        [ 0.10500698,  0.20100361,  2.1611679 ,  0.82650768],
        [ 0.13466044,  0.09973709, -0.13249336,  0.22818664]],

       [[ 0.98302377, -0.59284012,  1.08936696,  0.01059501],
        [ 0.70185892, -0.45564688,  0.08166399,  1.58129395],
        [ 1.09322997,  0.33489117,  0.21590406, -0.60046835],
        [ 1.21443113, -1.43409111,  1.35239403, -1.2406792 ]],

       [[-0.56288627, -0.82753418, -1.1841007 ,  0.92405182],
        [-0.15840512, -0.8818495 , -0.96063463,  0.69249953],
        [ 1.03547077, -0.27060784,  0.98717298,  0.30969918],
        [-1.31784766,  0.73498552,  0.76353373,  0.64317985]]])

In [138]:
d = np.random.randn(3,4)

In [139]:
pd.DataFrame(d)

0         1         2         3
0 -0.868491 -0.595855 -0.097689 -0.383793
1 -1.686248  1.315166 -0.067621  0.622151
2  1.004113  0.058830 -0.147368  1.179939

In [134]:
np.random.randn(3,4,4).mean()

-0.1630036310720872

In [140]:
d1 = np.random.randint(0,10,(4,4,2))

In [141]:
d1

array([[[8, 5],
        [3, 3],
        [2, 8],
        [2, 4]],

       [[7, 9],
        [1, 0],
        [2, 3],
        [4, 1]],

       [[0, 2],
        [0, 2],
        [8, 1],
        [8, 6]],

       [[0, 1],
        [4, 7],
        [8, 6],
        [9, 7]]])

In [142]:
d1.reshape(8,4) # must be multiple 4X4X2

array([[8, 5, 3, 3],
       [2, 8, 2, 4],
       [7, 9, 1, 0],
       [2, 3, 4, 1],
       [0, 2, 0, 2],
       [8, 1, 8, 6],
       [0, 1, 4, 7],
       [8, 6, 9, 7]])

In [143]:
d1.reshape(8,-3) # must be a multiple

array([[8, 5, 3, 3],
       [2, 8, 2, 4],
       [7, 9, 1, 0],
       [2, 3, 4, 1],
       [0, 2, 0, 2],
       [8, 1, 8, 6],
       [0, 1, 4, 7],
       [8, 6, 9, 7]])

In [145]:
d1.reshape(2,16)

array([[8, 5, 3, 3, 2, 8, 2, 4, 7, 9, 1, 0, 2, 3, 4, 1],
       [0, 2, 0, 2, 8, 1, 8, 6, 0, 1, 4, 7, 8, 6, 9, 7]])

In [146]:
d1.reshape(1,-1)

array([[8, 5, 3, 3, 2, 8, 2, 4, 7, 9, 1, 0, 2, 3, 4, 1, 0, 2, 0, 2, 8, 1,
        8, 6, 0, 1, 4, 7, 8, 6, 9, 7]])

In [148]:
pd.DataFrame(d1.reshape(1,-1))

0   1   2   3   4   5   6   7   8   9   ...  22  23  24  25  26  27  28  \
0   8   5   3   3   2   8   2   4   7   9  ...   8   6   0   1   4   7   8   

   29  30  31  
0   6   9   7  

[1 rows x 32 columns]